//! The committed device fixture must contain **no part of the answer**.
//!
//! `examples/kiss_device_fixture.rs` states that rule in prose. Prose carries no
//! instrument: a later edit that added a convenience field — a decoded op-class
//! string, a pre-sorted array, an assembled suffix — would still generate, still
//! parse, and still look like a fixture. This file is the instrument.
//!
//! # Why the rule is load-bearing rather than stylistic
//!
//! KISS umbrella §5.3 condition 1 (per KISS #221) counts derivers **per field**,
//! and says a party that receives a value and reproduces it byte-exactly shows
//! faithful *passthrough*, not independent derivation. The whole purpose of this
//! fixture is to let a second party derive a `vulkan:` capability set without
//! loading Vulkan. If the file carried any derived fragment, that party would be
//! copying it, condition 1 would fail on exactly that fragment, and the failure
//! would be invisible — the two tokens would byte-match perfectly, which is the
//! symptom rather than the refutation.
//!
//! # These tests need no GPU
//!
//! They read the committed artifact, so they run everywhere CI runs. That is
//! deliberate: the fixture can only be *regenerated* on the hardware it
//! describes, but it can be *policed* anywhere, and the policing is the part
//! that must never be skipped.

use std::path::PathBuf;

fn fixture() -> String {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("fixtures")
        .join("kiss-device-fixture.json");
    std::fs::read_to_string(&path).unwrap_or_else(|e| {
        panic!(
            concat!(
                "cannot read the committed device fixture at {}: {}\n",
                "It is generated by `cargo run --example kiss_device_fixture` on ",
                "a machine with real hardware and committed as data. If it was ",
                "deleted, restore it rather than deleting this test — the test ",
                "is what keeps the file honest."
            ),
            path.display(),
            e
        )
    })
}

/// The keys whose values are legitimately strings. **Everything else in the
/// fixture must be a number or a bool.**
///
/// This is the allowlist that makes
/// [`no_unexpected_field_carries_a_string_value`] a statement about the
/// *property* rather than about a list of forbidden spellings. Adding a key
/// here is a deliberate act; forgetting to add a forbidden spelling to a
/// denylist is an omission, and the two fail in opposite directions.
const STRING_VALUED_KEYS: &[&str] = &[
    "schema",
    "note",
    "instance_api_version",
    "vulkane_version",
    "device_name",
    "device_api_version",
    "status",
    "error",
];

/// Every vocabulary value is a **number**, so any unexpected string is suspect.
///
/// This is the guard that actually pins "nothing token-shaped", and it replaces
/// a denylist that could only ever be as complete as its author remembered to
/// make it. The previous version enumerated `sg32`/`sg64` and a subset of the
/// component spellings — so `sgdyn`, `sg128`, and every one of `i16`/`i32`/
/// `i64`/`u16`/`u32`/`u64` would have leaked through a guard that reported
/// clean. Both gaps were found in review.
///
/// **That is this file's own finding turned on itself.** `kiss-vulkan-vocab`'s
/// `the_named_table_is_complete_and_matches_the_registered_set` exists because
/// identity-pinning catches a *wrong* entry and is structurally blind to a
/// *missing* one; a denylist has exactly that shape, and this one already had
/// eight holes. Enumerating what is *permitted* is bounded and reviewable;
/// enumerating what is *forbidden* is unbounded and silently incomplete.
///
/// It matters most precisely here. The fixture's entire value is that a second
/// party can derive `target` from it **without receiving any step of our
/// derivation**, and this guard is the only thing between "an independent
/// derivation" and "a derivation that quietly reused ours". A leak it cannot
/// see would let the fixture satisfy KISS umbrella §5.3 condition 1 while
/// failing it in fact — which is the case #221 was written to catch.
#[test]
fn no_unexpected_field_carries_a_string_value() {
    let text = fixture();

    for (i, _) in text.match_indices("\": ") {
        // Walk back over the key to its opening quote.
        let before = &text[..i];
        let Some(start) = before.rfind('"') else {
            continue;
        };
        let key = &before[start + 1..];
        let value_starts_at = i + "\": ".len();
        let is_string = text[value_starts_at..].starts_with('"');

        if is_string && !STRING_VALUED_KEYS.contains(&key) {
            let preview: String = text[value_starts_at..]
                .chars()
                .take(60)
                .collect::<String>()
                .replace('\n', " ");
            panic!(
                concat!(
                    "the device fixture has key {:?} carrying a STRING value: {}\n\n",
                    "Every value the vocabulary would spell must appear as the raw ",
                    "number the driver reported. A string here is either a ",
                    "vocabulary spelling (`f16`, `i8packed`, `sgdyn`, …), an ",
                    "assembled token fragment, or a new field nobody vetted — and ",
                    "the spelling IS the derivation.\n\n",
                    "If this key genuinely holds prose, add it to ",
                    "STRING_VALUED_KEYS deliberately. Do not delete this check: a ",
                    "denylist of forbidden spellings is what this replaced, and it ",
                    "had eight holes in it."
                ),
                key, preview
            );
        }
    }
}

/// Assembled token fragments, which can hide inside the free-text fields the
/// allowlist above permits.
///
/// Scoped deliberately: this catches what
/// [`no_unexpected_field_carries_a_string_value`] cannot see, namely a fragment
/// embedded in `note` or a device name, rather than standing in as the general
/// guard. The claim in the doc comment is exactly what the code tests — the
/// earlier version of this file claimed "nothing token-shaped" while testing
/// two subgroup widths and a partial spelling list, and a claim wider than its
/// evidence is worse than no claim, because the next reader trusts it and never
/// audits the list.
#[test]
fn no_assembled_token_fragment_appears_anywhere() {
    let text = fixture();

    for needle in ["vulkan:", "ops-", "arith-", "cm-", "cv-", "fnv1a64"] {
        assert!(
            !text.contains(needle),
            concat!(
                "the device fixture contains {:?}, which is an assembled token ",
                "fragment. The fixture is the INPUT to a derivation and must ",
                "carry no part of its output: a second party consuming it would ",
                "be performing passthrough on this fragment, and KISS umbrella ",
                "§5.3 condition 1 counts that as zero independent derivers for ",
                "the field."
            ),
            needle
        );
    }

    // `sg` followed by a width or `dyn` — the whole family, not two examples.
    // `sgdyn` is the width-agnostic spelling and `sg128` is a width no device
    // reports today; both are as much a leak as `sg64`, and the previous
    // hard-coded pair would have passed either.
    for (i, _) in text.match_indices("sg") {
        let rest = &text[i + 2..];
        let leak = rest.starts_with("dyn")
            || rest
                .chars()
                .next()
                .is_some_and(|c: char| c.is_ascii_digit());
        assert!(
            !leak,
            concat!(
                "the device fixture contains a subgroup token spelling at byte ",
                "{}: {:?}. The subgroup field is derived from ",
                "`subgroup_size` and the size-control range; the fixture carries ",
                "those as numbers and must not carry the spelling they produce."
            ),
            i,
            rest.chars().take(12).collect::<String>()
        );
    }
}

/// A derived predicate is as much a leak as a spelling is.
///
/// `has_any_int8_acceleration()` is an OR over six of the sixteen dot-product
/// bools, and `arith-dot8` is downstream of that OR. Emitting the OR instead of
/// the bools would hand the consumer a step. This also guards the sixteen
/// individual bools being present, since dropping fifteen and keeping the
/// reduction is the tempting simplification.
#[test]
fn fixture_carries_raw_dot_product_bools_not_the_reduction() {
    let text = fixture();

    assert!(
        !text.contains("has_any_int8") && !text.contains("any_int8_acceleration"),
        concat!(
            "the device fixture emits a reduced int8-acceleration predicate. ",
            "That OR is a derivation step and `arith-dot8` depends on it — the ",
            "consumer must run it themselves. Emit all sixteen dot-product ",
            "bools individually."
        )
    );

    // The two devices disagree about WHICH disjuncts are set, which is what
    // makes the fixture able to catch a partial implementation of the OR. The
    // AMD part sets the plain 8-bit bools; the NVIDIA part sets none of them
    // and reaches the same conclusion only through the 4x8-bit-packed ones. A
    // consumer that implemented the OR as "the three 8-bit checks" would derive
    // dot8 correctly on one device and wrongly on the other.
    assert!(
        text.contains("\"dot_product_8bit_unsigned\": true"),
        "no device in the fixture sets dot_product_8bit_unsigned; the fixture \
         has lost its coverage of the plain 8-bit disjuncts"
    );
    assert!(
        text.contains("\"dot_product_8bit_unsigned\": false"),
        concat!(
            "every device in the fixture sets dot_product_8bit_unsigned. The ",
            "fixture no longer covers the case where int8 acceleration is ",
            "reachable ONLY through the 4x8-bit-packed disjuncts, which is how ",
            "the NVIDIA part reports it — a consumer implementing the OR as ",
            "just the three 8-bit checks would pass against this fixture."
        )
    );
    assert!(
        text.contains("\"dot_product_4x8bit_packed_unsigned\": true"),
        "no device sets dot_product_4x8bit_packed_unsigned; the packed \
         disjuncts are uncovered"
    );
}

/// Canonical ordering is part of the derivation, so the arrays must arrive in
/// driver report order.
///
/// `DeviceCapabilities::of` sorts and dedups both cooperative arrays, because
/// driver order is not guaranteed stable and the token must be byte-identical
/// regardless. That sort is a step the second deriver has to take. A fixture
/// that arrived pre-sorted would donate it — and would do so invisibly, since a
/// sorted array is not obviously wrong.
///
/// Proven by counter-example rather than asserted: the fixture's cooperative
/// arrays are demonstrably *not* in sorted order.
#[test]
fn cooperative_arrays_are_in_driver_order_not_canonical_order() {
    let text = fixture();

    let ms = numbers_after(&text, "\"m\": ");
    assert!(
        ms.len() >= 4,
        "expected several cooperative-matrix shapes in the fixture, found {}",
        ms.len()
    );

    // The `k` sequence on a real device interleaves (16, 16, 8, 16, ...). If it
    // ever comes back non-decreasing across the whole file, either the hardware
    // changed or something canonicalized the array on the way out.
    let ks = numbers_after(&text, "\"k\": ");
    assert!(
        !is_sorted(&ks),
        concat!(
            "the cooperative-matrix shapes in the fixture are in sorted order. ",
            "Sorting is part of the token derivation (`DeviceCapabilities::of` ",
            "sorts and dedups), so a pre-sorted fixture hands the consumer a ",
            "step they are supposed to perform. Emit the driver's report order. ",
            "If a driver genuinely reports sorted shapes, replace this check ",
            "with one that pins the exact driver sequence — do not delete it."
        )
    );
}

/// The fixture must not fingerprint the machine it was captured on.
///
/// `deviceUUID` / `driverUUID` / `deviceLUID` / `pipelineCacheUUID` identify an
/// installation rather than a model of hardware, and this file is meant to be
/// handed to other projects. They are not deriver inputs either, so excluding
/// them costs nothing. `PhysicalDevice::device_identity` is simply never called.
#[test]
fn fixture_carries_no_machine_identifying_values() {
    let text = fixture().to_ascii_lowercase();
    for needle in ["uuid", "luid", "serial"] {
        assert!(
            !text.contains(needle),
            concat!(
                "the device fixture contains {:?}. UUIDs and LUIDs identify the ",
                "MACHINE, not the model of hardware, and this artifact is shared ",
                "across projects. vendor_id / device_id / device_name already ",
                "give provenance, and no identity value is a deriver input."
            ),
            needle
        );
    }
}

/// Two devices with different default subgroup widths, or the fixture cannot
/// catch the mistake it exists to catch.
#[test]
fn fixture_spans_at_least_two_distinct_subgroup_widths() {
    let text = fixture();
    let mut widths = numbers_after(&text, "\"subgroup_size\": ");
    widths.sort_unstable();
    widths.dedup();
    assert!(
        widths.len() >= 2,
        concat!(
            "the fixture reports {:?} — fewer than two distinct default ",
            "subgroup widths. A deriver that hardcoded one width would pass ",
            "against it. Capture on both an integrated and a discrete part ",
            "(the AMD 610M reports 64, the RTX 4070 reports 32)."
        ),
        widths
    );
}

/// Every `key` occurrence's following integer, in file order.
fn numbers_after(text: &str, key: &str) -> Vec<u64> {
    text.match_indices(key)
        .filter_map(|(i, _)| {
            let rest = &text[i + key.len()..];
            let end = rest.find(|c: char| !c.is_ascii_digit())?;
            rest[..end].parse().ok()
        })
        .collect()
}

fn is_sorted(v: &[u64]) -> bool {
    v.windows(2).all(|w| w[0] <= w[1])
}
